### ISSUE TITLE
Big Sur Installation in RecoveryOS freezes at "13 minutes remaining"

### ISSUE THREAD

**Issue by devojunky** [Narcoroni/Razer-Blade-2021-Hackintosh#1]
I have a Razer Blade 15 with identical specs besides the wifi/Bluetooth card. The installation freezes in RecoveryOS at "13 minutes remaining." Upon checking the installation log, nothing seems to be halting the installation process. Touchpad also fails to function in RecoveryOS. Attempting to boot into macOS Catalina results in the startup progress bar being at zero. Any fixes?

**Comment by Narcoroni** [comment]
My initial installation and boot were uneventful and worked on the first try. I build the USB using the dortania opencore guide. Can't really help you there.
I went with Big Sur though, it works well using opencore.
The touchpad not working in recovery is to be expected, I just used a USB mouse and ethernet adapter until I got everything running under MacOS.

**Comment by devojunky** [comment]
I also tried following the Dortania guide. Could the issue possibly be the WiFi/BT card since that is the only variable I can think of? And if so, how would I work around it?

**Comment by devojunky** [comment]
Also, have you made any changes to your boot drive?

**Comment by Narcoroni** [comment]
I added a second ssd for MacOS, so it was completely fresh and set up in accordance with the dortania guide. 

The wifi card is not the issue, I initially booted the hackintosh with the original Intel card without issue, before switching it out for the Broadcom.

I'd recommend making a new install USB with Big Sur from the dortania guide, making sure everything is correct.

**Comment by devojunky** [comment]
What is your second ssd?

**Comment by Narcoroni** [comment]
Sabrent Rocket 1TB NVMe PCIe M.2

**Comment by devojunky** [comment]
Ah, okay. That explains why it's not working for me. I have an unsupported SSD. Thank you.
