### ISSUE TITLE
L

### ISSUE THREAD

**Issue by tane123** [Narcoroni/Razer-Blade-2021-Hackintosh#4]
If you are going to steal my repo as your own could you please at least give me the rightful credit? I can tell you stole this because of the serial number is the same as the one in [my repo](https://github.com/tane123/Razer-Blade-15-Base-2021-Hackintosh) that was uploaded a month before yours and the file 'test.txt' still exists.

**Comment by Narcoroni** [comment]
Sorry you feel that way. 
The EFI  is a mix and match of multiple other ones, trying to get everything to play nice. By the end I had no clue what came from where. 

If you want the credits for some internet style points I'll throw it up there, I honestly don't care. Just posted the EFI to help other people out.

**Comment by tane123** [comment]
Sorry I went overboard with this. At the end of the day I don't/shouldn't care. You are right in saying you were trying to help others. Sorry for coming off as an a**hole. No credit is needed.
